name: Main workflow

on:
  push:
    branches: [ master, main, ]
  pull_request:
    branches: [ master, main, ]

jobs:

  build:
    name: Build
    runs-on: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      uses: actions/setup-python@v3

    - name: Run with setup-python 3.8.6
      uses: ./
      with:
        python-version: 3.8.6
        architecture: x64
    - name: Verify 3.8.6
    