on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  tests:
    name: Python
    runs-on: [ ubuntu-latest ]
    env:
      USING_COVERAGE: '3.6,3.8'


    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
                
