name: Main workflow

on:
  push:
    branches: [ master, main, ]
  pull_request:
    branches: [ master, main, ]

jobs:

  build:
    name: Build
    runs-on: [ubuntu-latest, windows-latest]
    steps:

      - uses: actions/checkout@v2
      
      - name: Run with setup-python 3.8.6
      - uses: ./
        with:
          python-version: 3.8.6
          architecture: x64

    